apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  devops.cloud.ibm.com/cd: kustomize
generatorOptions:
  disableNameSuffixHash: true
resources:
  - external-secrets.yaml
  - secret-store.yaml
configMapGenerator:
  - name: environment-properties
    envs:
      - environment-properties.env
