---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-listener-gitlab
spec:
  triggers:
    - bindings:
        - name: ci-binding
        - name: manual-trigger-binding
      template:
        name: ci-template