apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "external-secret"
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  refreshInterval: "0s"
  target:
    name: extsecrets
    creationPolicy: "Owner"
    deletionPolicy: "Delete"
  data:
  - secretKey: cos-api-key
    remoteRef:
      key: [insert-secret-name-in-vault]
      property: cos-api-key
  - secretKey: ibmcloud-api-key
    remoteRef:
      key: [insert-secret-name-in-vault]
      property: ibmcloud-api-key
  - secretKey: signing-key
    remoteRef:
      key: [insert-secret-name-in-vault]
      property: signing-key
