apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  devops.cloud.ibm.com/cd: kustomize
generatorOptions:
  disableNameSuffixHash: true
resources:
  - git-ci-timed-listener.yaml
  - git-ci-timed-binding.yaml
configMapGenerator:
  - name: git-ci-timed-props
    envs:
      - git-ci-timed-props.env
